In [27]:
import tensorflow as tf
import numpy as np

In [28]:
cells = tf.reshape(100 + tf.range(20), shape=(-1, 2))
cells

<tf.Tensor: shape=(10, 2), dtype=int32, numpy=
array([[100, 101],
       [102, 103],
       [104, 105],
       [106, 107],
       [108, 109],
       [110, 111],
       [112, 113],
       [114, 115],
       [116, 117],
       [118, 119]])>

In [29]:
anchors = tf.reshape(tf.range(6), shape=(3,-1))
anchors

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5]])>

In [30]:
expanded_anchors = tf.expand_dims(anchors, axis=0)
expanded_anchors

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[0, 1],
        [2, 3],
        [4, 5]]])>

In [31]:
expanded_cells = tf.expand_dims(cells, axis=1)
expanded_cells

<tf.Tensor: shape=(10, 1, 2), dtype=int32, numpy=
array([[[100, 101]],

       [[102, 103]],

       [[104, 105]],

       [[106, 107]],

       [[108, 109]],

       [[110, 111]],

       [[112, 113]],

       [[114, 115]],

       [[116, 117]],

       [[118, 119]]])>

In [32]:
shape = tf.broadcast_dynamic_shape(tf.shape(expanded_anchors), tf.shape(expanded_cells))
shape

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  3,  2])>

In [33]:
dimensions = tf.cast(tf.broadcast_to(expanded_anchors, shape=shape), dtype=tf.float32)
dimensions

<tf.Tensor: shape=(10, 3, 2), dtype=float32, numpy=
array([[[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]]], dtype=float32)>

In [34]:
locations = tf.cast(tf.broadcast_to(expanded_cells, shape=shape), dtype=tf.float32)
locations = (locations + 0.5) / 7 - dimensions / 2

In [35]:
tf.concat((locations, dimensions), axis=2)

<tf.Tensor: shape=(10, 3, 4), dtype=float32, numpy=
array([[[14.357142, 14.      ,  0.      ,  1.      ],
        [13.357142, 13.      ,  2.      ,  3.      ],
        [12.357142, 12.      ,  4.      ,  5.      ]],

       [[14.642858, 14.285714,  0.      ,  1.      ],
        [13.642858, 13.285714,  2.      ,  3.      ],
        [12.642858, 12.285714,  4.      ,  5.      ]],

       [[14.928572, 14.571428,  0.      ,  1.      ],
        [13.928572, 13.571428,  2.      ,  3.      ],
        [12.928572, 12.571428,  4.      ,  5.      ]],

       [[15.214286, 14.857142,  0.      ,  1.      ],
        [14.214286, 13.857142,  2.      ,  3.      ],
        [13.214286, 12.857142,  4.      ,  5.      ]],

       [[15.5     , 15.142858,  0.      ,  1.      ],
        [14.5     , 14.142858,  2.      ,  3.      ],
        [13.5     , 13.142858,  4.      ,  5.      ]],

       [[15.785714, 15.428572,  0.      ,  1.      ],
        [14.785714, 14.428572,  2.      ,  3.      ],
        [13.785714, 