###  Created by Luis A. Sanchez-Perez (alejand@umich.edu).
<p><span style="color:green"><b>Copyright &#169;</b> Do not distribute or use without authorization from author.</span></p>

### Convolution (Discrete)
The convolution operator is often seen in signal processing, where it models the effect of a linear time-invariant system on a signal. In probability theory, the sum of two independent random variables is distributed according to the convolution of their individual distributions.

The discrete convolution operation is defined as

$$ \begin{equation} \label{1} (a * v)[n] = \sum_{m = -\infty}^{\infty} a[m] v[n - m] \end{equation} $$


It can be shown that a convolution \\( x(t) * y(t) \\) in time/space is equivalent to the multiplication \\( X(f) Y(f)\\)  in the Fourier domain, after appropriate padding (padding is necessary to prevent circular convolution). Since multiplication is more efficient (faster) than convolution, the function scipy.signal.fftconvolve exploits the FFT to calculate the convolution of large data-sets.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
arr1 = [1, 2, 3, 4]
arr2 = [0, 1, 0.2]

In [3]:
print(arr1[::-1])
print(arr2)

[4, 3, 2, 1]
[0, 1, 0.2]


In [4]:
np.convolve(arr1,arr2)

array([0. , 1. , 2.2, 3.4, 4.6, 0.8])

In [5]:
np.convolve(arr2, arr1)

array([0. , 1. , 2.2, 3.4, 4.6, 0.8])

In [6]:
np.convolve(arr1, arr2, 'same')

array([1. , 2.2, 3.4, 4.6])

In [7]:
np.convolve(arr1, arr2, 'valid')

array([2.2, 3.4])